[build]
  command = "npm run build"
  publish = "web/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "fastify",
    "@fastify/cors",
    "@supabase/supabase-js",
    "pg",
    "zod",
    "serverless-http"
  ]
  included_files = ["server/dist/**"]

# Specific function route (match your file name!)
[[redirects]]
  from = "/api/gh-dispatch"
  to   = "/.netlify/functions/gh-dispatch"
  status = 200

# Everything else under /api goes to your Fastify server
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/server"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200