[build]
  command = "npm run build"
  publish = "web/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["fastify", "@fastify/cors", "@supabase/supabase-js", "pg", "zod", "serverless-http"]
  included_files = ["server/dist/**"]

[[functions]]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
